# =============================================================================
stages:
  - clean
  - build

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 10
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
  CI_ENVIRONMENT: Prod
  NugetFeed: MapPSGallery
  NugetApiKey: GxLd2ectjnjfyJ0tu9xe
  NugetApiUrl: "https://repo.windows.mapcom.local/nuget/powershell/"

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  untracked: true
  paths:
    - BuildOutput
  policy: pull-push

# -----------------------------------------------------------------------------
# STAGE: CLEAN
# -----------------------------------------------------------------------------
clean:
  stage: clean
  script:
    - .\Build.ps1 -Tasks CleanBuildOutput
  cache:
    <<: *global_cache
  only:
    - master

# -----------------------------------------------------------------------------
# STAGE: BUILD
# -----------------------------------------------------------------------------
build:
  stage: build
  script:
    - .\Build.ps1 -ResolveDependency
  cache:
    <<: *global_cache
  artifacts:
    reports:
      junit: ["BuildOutput/IntegrationTestResults.xml", "BuildOutput/AcceptanceTestResults.xml"]
  only:
    - master